# Generated by Django 5.2.1 on 2025-05-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_problem_slug_problem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('CPP', 'C++'), ('PY', 'Python')], default='CPP', help_text='Select your language', max_length=3),
        ),
    ]
