branch-defaults:
  master:
    environment: myjudge-env
    # group_suffix can stay null
    group_suffix: null

global:
  application_name: myjudge-app
  default_region: ap-south-1
  default_platform: docker
  profile: default
  workspace_type: Application
